### ISSUE TITLE
Make filterUser optional?

### ISSUE THREAD

**Issue by mikebronner** [Ardiannn08/resolve-outdated-comment#1]
Hi, is it possible to have filterUser be optional, so that if not provided, will handle all resolved comments?

Thanks!

**Comment by Ardiannn08** [comment]
Hi @mikebronner, I apologize for the delay in completing it. I wasn't able to check this repository earlier. The required updates should be provided in this version: https://github.com/Ardiannn08/resolve-outdated-comment/releases/tag/v1.2.  PR Changes: https://github.com/Ardiannn08/resolve-outdated-comment/pull/4
Please update the version tag accordingly. Thank you for bringing up the issues!"
