### ISSUE TITLE
Allow multiple users to be filtered.

### ISSUE THREAD

**Issue by mikebronner** [Ardiannn08/resolve-outdated-comment#2]
It would be very helpful to allow multiple users to be configured, so that many different bots and manual reviewers could be resolved at the same time.

**Comment by makslevental** [comment]
Just run it twice

**Comment by Ardiannn08** [comment]
Hi @mikebronner, @makslevental , this PR should allow multiple users: https://github.com/Ardiannn08/resolve-outdated-comment/pull/5 , updated on tag version v1.2

Please update the version tag to the latest. Thank you for bringing up the issues!"
