### ISSUE TITLE
`Node.js 16 actions are deprecated` warning

### ISSUE THREAD

**Issue by xuwei-k** [Ardiannn08/resolve-outdated-comment#3]
- https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
- https://github.com/Ardiannn08/resolve-outdated-comment/blob/f166e7d2da880b2410df42501a678910f2a1e6ca/action.yml#L14

**Comment by Ardiannn08** [comment]
Hi @xuwei-k, thank you for bringing up the issues! The Node.js version should be updated to the newest release tag `v1.2`. Please check it.
